import test from "node:test"; import assert from "node:assert/strict";
import { createHandler } from "../worker/src/index.js"; import { normalizeName } from "../worker/src/normalize.js";
function memoryRepo({ambiguous=false,existing=false}={}){const party={id:1,publicId:"synthetic-public-id-0123456789abcdef",name:"Example Household",guests:[{id:10,name:"Alex Example",attending:existing?"yes":null,dinnerChoice:existing?"beef":null,dietaryRestrictions:""},{id:11,name:"Taylor Example",attending:existing?"no":null,dinnerChoice:null,dietaryRestrictions:""}],rsvp:existing?{contactEmail:"alex@example.test",addressLine1:"1 Test Way",addressLine2:"",city:"Ottawa",provinceState:"ON",postalCode:"A1A 1A1",country:"Canada",message:"Hello"}:null};return{party,saves:[],async lookup(n){return !ambiguous&&n==="alex example"?party:null},async byPublicId(id){return id===party.publicId?party:null},async save(...a){this.saves.push(a)}}}
const valid=r=>({partyId:r.party.publicId,contactEmail:"person@example.test",addressLine1:"1 Test Way",addressLine2:"",city:"Ottawa",provinceState:"ON",postalCode:"A1A 1A1",country:"Canada",message:"",website:"",turnstileToken:"ok",guests:[{id:10,attending:"yes",dinnerChoice:"chicken",dietaryRestrictions:"none"},{id:11,attending:"no",dinnerChoice:null,dietaryRestrictions:""}]});
function setup(o={}){const repo=o.repo||memoryRepo(o), handler=createHandler({repository:repo,verifyTurnstile:async t=>t==="ok",limited:o.limited||(async()=>false)});return{repo,call:(path,body)=>handler(new Request(`https://x.test/api/rsvp/${path}`,{method:"POST",headers:{"content-type":"application/json"},body:typeof body==="string"?body:JSON.stringify(body)}),{})}}
test("name normalization",()=>assert.equal(normalizeName("  Àlex—O’Neil "),"alex o'neil"));
test("successful name lookup",async()=>{const{call}=setup(),r=await call("lookup",{name:"Alex Example",turnstileToken:"ok",website:""});assert.equal(r.status,200);assert.equal((await r.json()).party.guests.length,2)});
test("unknown and ambiguous lookup have generic errors",async()=>{for(const o of [{},{ambiguous:true}]){const{call}=setup(o),r=await call("lookup",{name:o.ambiguous?"Alex Example":"Unknown Person",turnstileToken:"ok",website:""});assert.equal(r.status,404);assert.match((await r.json()).message,/could not find/)}});
test("loads existing RSVP",async()=>{const{call}=setup({existing:true}),d=await(await call("lookup",{name:"Alex Example",turnstileToken:"ok",website:""})).json();assert.equal(d.party.rsvp.contactEmail,"alex@example.test");assert.equal(d.party.guests[0].dinnerChoice,"beef")});
test("first submission uses server timestamp",async()=>{const{repo,call}=setup();assert.equal((await call("submit",valid(repo))).status,200);assert.equal(repo.saves.length,1);assert.match(repo.saves[0][2],/^\d{4}-/);assert.equal(repo.saves[0][1].guests[1].dinner,null)});
test("updates through upsert save path",async()=>{const{repo,call}=setup({existing:true}),b=valid(repo);b.guests[0].dinnerChoice="vegetarian";assert.equal((await call("submit",b)).status,200);assert.equal(repo.saves[0][1].guests[0].dinner,"vegetarian")});
for(const [title,mutate,status] of [
 ["manipulated party",b=>b.partyId="wrong",404],["manipulated guest",b=>b.guests[0].id=999,400],["guest from wrong party",b=>b.guests[1].id=12,400],
 ["missing attendance",b=>delete b.guests[0].attending,400],["invalid attendance",b=>b.guests[0].attending="maybe",400],["attending without dinner",b=>b.guests[0].dinnerChoice=null,400],
 ["declining with dinner",b=>b.guests[1].dinnerChoice="beef",400],["invalid dinner",b=>b.guests[0].dinnerChoice="fish",400],["malformed email",b=>b.contactEmail="bad",400]
])test(`rejects ${title}`,async()=>{const{repo,call}=setup(),b=valid(repo);mutate(b);assert.equal((await call("submit",b)).status,status)});
test("rejects each required mailing field",async()=>{for(const k of ["addressLine1","city","provinceState","postalCode","country"]){const{repo,call}=setup(),b=valid(repo);b[k]="";assert.equal((await call("submit",b)).status,400,k)}});
test("honeypot triggered",async()=>{const{call}=setup();assert.equal((await call("lookup",{name:"Alex Example",turnstileToken:"ok",website:"bot"})).status,400)});
test("Turnstile failure",async()=>{const{call}=setup();assert.equal((await call("lookup",{name:"Alex Example",turnstileToken:"bad",website:""})).status,400)});
test("malformed JSON",async()=>{const{call}=setup();assert.equal((await call("lookup","{bad")).status,400)});
test("rate limit",async()=>{const{call}=setup({limited:async()=>true});assert.equal((await call("lookup",{})).status,429)});
